trigger: none
pr: none

parameters:
  - name: publishLocalizationFile
    type: boolean
    default: true

variables:
# Variable group contains the PAT to LOC
- group: OneLocBuildVariables

jobs:
- job: Localization
  pool:
    name: NetCore1ESPool-Svc-Internal
    demands: ImageOverride -equals windows.vs2022preview.amd64
  steps:
  - task: NodeTool@0
    displayName: 'Install Node.js 16.x'
    inputs:
      versionSpec: '16.x'
  - checkout: self
    clean: true
    submodules: true
    fetchTags: false
    fetchDepth: 0
  - script: npm install @vscode/l10n-dev
    displayName: 'Install l10n-dev'
  - script: npm run l10nDevGenerateLocalizationBundle
    displayName: 'Generate bundle.l10.json'
  - script: npm run l10nDevGenerateXlf
    displayName: 'Generate xlf files from bundle.10n.json'
  - task: OneLocBuild@2
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      locProj: loc/LocProject.json
      outDir: '$(Build.SourcesDirectory)/loc'
      isCreatePrSelected: false
      patVariable: $(dn-bot-ceapex-package-r)
      packageSourceAuth: patAuth
      lclSource: lclFilesfromPackage
      LclPackageId: 'LCL-JUNO-PROD-VSCODECS'
  - script: npm run l10nDevImportXlf
    displayName: 'Import xlf to json.'
  - task: PublishBuildArtifacts@1
    displayName: 'Publish Localization Files'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/loc'
      PublishLocation: Container
      ArtifactName: Loc
    condition: ${{ parameters.publishLocalizationFile }}
  - task: PublishBuildArtifacts@1
    displayName: 'Publish l10n file'
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)/l10n'
      PublishLocation: Container
      ArtifactName: l10n
    condition: ${{ parameters.publishLocalizationFile }}


    # TODO import and create PR if needed
